"""Initial migration.

Revision ID: 16c244438906
Revises: 
Create Date: 2025-05-23 22:13:01.442457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c244438906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    # ### end Alembic commands ###
